[2025-10-15T02:12:29.692+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-15T02:12:29.731+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_etl.generate_dummy_data scheduled__2025-10-14T02:00:00+00:00 [queued]>
[2025-10-15T02:12:29.737+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_etl.generate_dummy_data scheduled__2025-10-14T02:00:00+00:00 [queued]>
[2025-10-15T02:12:29.738+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-15T02:12:29.749+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_dummy_data> on 2025-10-14 02:00:00+00:00
[2025-10-15T02:12:29.754+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_etl', 'generate_dummy_data', 'scheduled__2025-10-14T02:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/daily_etl_dag.py', '--cfg-path', '/tmp/tmp0kvk7vel']
[2025-10-15T02:12:29.757+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=303) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-15T02:12:29.757+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask generate_dummy_data
[2025-10-15T02:12:29.757+0000] {standard_task_runner.py:64} INFO - Started process 307 to run task
[2025-10-15T02:12:29.840+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_etl.generate_dummy_data scheduled__2025-10-14T02:00:00+00:00 [running]> on host 93e2d09e8883
[2025-10-15T02:12:30.104+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_etl' AIRFLOW_CTX_TASK_ID='generate_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-14T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-14T02:00:00+00:00'
[2025-10-15T02:12:30.104+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-15T02:12:30.134+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-15T02:12:30.135+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-15T02:12:30.151+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=daily_etl, task_id=generate_dummy_data, run_id=scheduled__2025-10-14T02:00:00+00:00, execution_date=20251014T020000, start_date=20251015T021229, end_date=20251015T021230
[2025-10-15T02:12:30.171+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-15T02:12:30.198+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-15T02:12:30.205+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
